"""Fetch the UI webfonts from Google Fonts and self-host them.

Why: loading fonts from fonts.googleapis.com means the desktop app makes a
network request on every start, silently falls back to a system font when
offline, and forces two holes into the CSP (style-src + font-src). Both
families are OFL-licensed, so redistributing them is fine.

Only the `latin` and `latin-ext` subsets are downloaded -- CJK text falls back
to system fonts through the font stack in style.css, so the cyrillic /
devanagari / vietnamese subsets would be dead weight.

Space Grotesk is a variable font: Google serves the *same* file for every
requested weight, so identical payloads are collapsed into one file with a
`font-weight: <min> <max>` range instead of four duplicate @font-face rules.

Usage (from the repo root):
    python scripts/fetch_webfonts.py
"""

from __future__ import annotations

import hashlib
import pathlib
import re
import urllib.request

# A modern UA is required or Google serves woff (not woff2) and no unicode-range.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

FAMILIES = [
    ("Space Grotesk", "400;500;600;700"),
    ("Rajdhani", "500;600;700"),
]

KEEP_SUBSETS = {"latin", "latin-ext"}

# Never touch the icon font; it is generated by generate_mdi_subset.py.
KEEP_FILES = {"materialdesignicons-subset.woff2"}

CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    + "&".join(f"family={name.replace(' ', '+')}:wght@{weights}" for name, weights in FAMILIES)
    + "&display=swap"
)

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "public" / "fonts"
CSS_OUT = ROOT / "src" / "assets" / "fonts.css"

BLOCK_RE = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", re.DOTALL)


def fetch(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        return response.read()


def field(block: str, prop: str) -> str:
    match = re.search(rf"{prop}:\s*([^;]+);", block)
    if match is None:
        raise ValueError(f"missing {prop} in @font-face block:\n{block}")
    return match.group(1).strip()


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)

    # Remove previously generated fonts so renamed/deduped files don't linger.
    for stale in FONT_DIR.glob("*.woff2"):
        if stale.name not in KEEP_FILES:
            stale.unlink()

    css = fetch(CSS_URL).decode("utf-8")

    # (family, subset) -> {weight: (url, unicode_range)}
    groups: dict[tuple[str, str], dict[str, tuple[str, str]]] = {}
    for subset, block in BLOCK_RE.findall(css):
        if subset not in KEEP_SUBSETS:
            continue
        family = field(block, "font-family").strip("'\"")
        weight = field(block, "font-weight")
        url_match = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if url_match is None:
            continue
        unicode_range = field(block, "unicode-range") if "unicode-range" in block else ""
        groups.setdefault((family, subset), {})[weight] = (url_match.group(1), unicode_range)

    rules: list[str] = []
    for (family, subset), weights in groups.items():
        slug = family.lower().replace(" ", "-")

        # Download each weight once and fingerprint it to spot variable fonts.
        payloads: dict[str, tuple[bytes, str]] = {}
        for weight, (url, unicode_range) in weights.items():
            payload = fetch(url)
            payloads[weight] = (payload, unicode_range)

        digests = {hashlib.md5(p).hexdigest() for p, _ in payloads.values()}
        numeric = sorted(int(w) for w in weights)

        if len(digests) == 1:
            # Variable font: one file, one rule spanning the weight range.
            filename = f"{slug}-{subset}.woff2"
            payload, unicode_range = next(iter(payloads.values()))
            (FONT_DIR / filename).write_bytes(payload)
            print(f"  {filename}  ({len(payload)} bytes, weights {numeric[0]}-{numeric[-1]})")
            entries = [(f"{numeric[0]} {numeric[-1]}", filename, unicode_range)]
        else:
            entries = []
            for weight in sorted(weights, key=int):
                payload, unicode_range = payloads[weight]
                filename = f"{slug}-{weight}-{subset}.woff2"
                (FONT_DIR / filename).write_bytes(payload)
                print(f"  {filename}  ({len(payload)} bytes)")
                entries.append((weight, filename, unicode_range))

        for weight_range, filename, unicode_range in entries:
            range_line = f"  unicode-range: {unicode_range};\n" if unicode_range else ""
            rules.append(
                "@font-face {\n"
                f"  font-family: '{family}';\n"
                "  font-style: normal;\n"
                f"  font-weight: {weight_range};\n"
                "  font-display: swap;\n"
                f'  src: url("/fonts/{filename}") format("woff2");\n'
                f"{range_line}"
                "}\n"
            )

    header = (
        "/* Self-hosted UI webfonts. Generated by scripts/fetch_webfonts.py -- do not edit by hand.\n"
        "   Space Grotesk and Rajdhani are both SIL Open Font License 1.1 (redistributable). */\n"
    )
    CSS_OUT.write_text(header + "\n".join(rules), encoding="utf-8")
    print(f"\nwrote {CSS_OUT.relative_to(ROOT)} with {len(rules)} @font-face rules")


if __name__ == "__main__":
    main()
