#!/usr/bin/env python3
"""重新生成 RustWallhub 的 Material Design Icons 子集。

用法（需安装 fonttools/pyftsubset）:
    python3 scripts/generate_mdi_subset.py
"""
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Vuetify 默认图标中本项目组件可能用到的集合（含分页/下拉/清空/排序等）。
VUETIFY_DEFAULTS = {
    "mdi-arrow-down", "mdi-arrow-left", "mdi-arrow-right", "mdi-arrow-up",
    "mdi-checkbox-blank-outline", "mdi-checkbox-marked", "mdi-chevron-down",
    "mdi-chevron-left", "mdi-chevron-right", "mdi-chevron-up", "mdi-close",
    "mdi-close-circle", "mdi-menu-down", "mdi-menu-right", "mdi-page-first",
    "mdi-page-last", "mdi-unfold-more-horizontal", "mdi-alert-circle",
    "mdi-check", "mdi-check-circle", "mdi-circle", "mdi-information",
    "mdi-magnify", "mdi-menu", "mdi-plus", "mdi-minus", "mdi-pencil",
    "mdi-star", "mdi-star-outline", "mdi-star-half-full", "mdi-radiobox-blank",
    "mdi-radiobox-marked", "mdi-pause", "mdi-play", "mdi-cached",
    "mdi-paperclip", "mdi-calendar", "mdi-keyboard-return",
    "mdi-keyboard-space", "mdi-fullscreen", "mdi-fullscreen-exit",
    "mdi-volume-high", "mdi-volume-low", "mdi-volume-medium",
    "mdi-volume-variant-off", "mdi-backspace", "mdi-cloud-upload",
    "mdi-eyedropper", "mdi-apple-keyboard-command", "mdi-apple-keyboard-control",
    "mdi-apple-keyboard-option", "mdi-apple-keyboard-shift",
}

def find_font_css():
    for pattern in [
        "node_modules/@mdi/font/css/materialdesignicons.css",
        "node_modules/.deno/@mdi+font@7.4.47/node_modules/@mdi/font/css/materialdesignicons.css",
    ]:
        path = ROOT / pattern
        if path.exists():
            return path
    sys.exit("找不到 @mdi/font 的 materialdesignicons.css")

def find_font():
    css = find_font_css()
    font = css.parents[1] / "fonts" / "materialdesignicons-webfont.woff2"
    if not font.exists():
        sys.exit(f"找不到字体文件: {font}")
    return font

def main():
    used = set()
    for path in (ROOT / "src").rglob("*"):
        if path.suffix in {".vue", ".ts"}:
            text = path.read_text(errors="ignore")
            used.update(re.findall(r"[\"'](mdi-[a-z0-9-]+)[\"']", text))
    icons = sorted(used | VUETIFY_DEFAULTS)

    css_text = find_font_css().read_text()
    rules = {}
    for m in re.finditer(r'\.(mdi-[a-z0-9-]+)::before\s*\{\s*content:\s*"\\F([0-9A-F]+)";\s*\}', css_text):
        rules[m.group(1)] = m.group(2)
    missing = [name for name in icons if name not in rules]
    if missing:
        sys.exit(f"以下图标在 MDI CSS 中不存在: {missing}")

    unicodes = ",".join(f"U+F{rules[name]}" for name in icons)
    out_font = ROOT / "public" / "fonts" / "materialdesignicons-subset.woff2"
    out_font.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "pyftsubset", str(find_font()), f"--unicodes={unicodes}",
            "--flavor=woff2", f"--output-file={out_font}",
        ],
        check=True,
    )

    lines = [
        "/* Material Design Icons subset: generated by scripts/generate_mdi_subset.py. */",
        "@font-face {",
        '  font-family: "Material Design Icons";',
        '  src: url("/fonts/materialdesignicons-subset.woff2") format("woff2");',
        "  font-weight: normal;",
        "  font-style: normal;",
        "  font-display: block;",
        "}",
        "",
        ".mdi:before,",
        ".mdi-set {",
        "  display: inline-block;",
        '  font: normal normal normal 24px/1 "Material Design Icons";',
        "  font-size: inherit;",
        "  text-rendering: auto;",
        "  line-height: inherit;",
        "  -webkit-font-smoothing: antialiased;",
        "  -moz-osx-font-smoothing: grayscale;",
        "}",
    ]
    lines += [f'.{name}::before {{ content: "\\F{rules[name]}"; }}' for name in icons]
    (ROOT / "src" / "assets" / "mdi-subset.css").write_text("\n".join(lines) + "\n")
    print(f"生成 {len(icons)} 个图标子集: {out_font.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
